version: '3.7'
services:
  delegacia-facil-postgresql:
    image: postgres:10.17
    container_name: delegacia-facil-postgresql
    environment:
      POSTGRES_DB: delegacia-facil
      POSTGRES_USER: oficina-futuro
      POSTGRES_PASSWORD: delegaciafacil
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    networks:
      - delegacia-facil-network

  delegacia-facil-flyway:
    image: flyway/flyway:6.3.1
    container_name: delegacia-facil-flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./migrate/changelogs:/flyway/sql
      - ./migrate/flyway.config:/flyway/conf/flyway.config
    environment:
      FLYWAY_URL: jdbc:postgresql://delegacia-facil-postgresql:5432/delegacia-facil
      FLYWAY_USER: oficina-futuro
      FLYWAY_PASSWORD: delegaciafacil
    depends_on:
      - delegacia-facil-postgresql
    networks:
      - delegacia-facil-network

networks:
  delegacia-facil-network:
    driver: bridge
